name: Test

env:
  RUBY_VERSION: "3.1.0"
  NODE_VERSION: "16.13.0"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
      - name: Run bundle install
        run: bin/bundle install
      - name: Run yarn install
        run: bin/yarn install
      - name: Compile Assets
        run: bin/rails assets:precompile
      - name: Run all tests
        run: bin/rspec
